# 管理侧
server:
  port: 7001
spring:
  application:
    name: admin
  # 服务治理
  cloud:
    nacos:
      server-addr: localhost:8848
  # 数据库
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shmily?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 233333
#    url: jdbc:mysql://82.156.231.128:3306/shmily?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
#    username: root
#    password: Waabd!23
    # Hikari
    hikari:
      connection-timeout: 10000
      validation-timeout: 3000
      idle-timeout: 60000
      login-timeout: 5
      max-lifetime: 60000
      maximum-pool-size: 10
      minimum-idle: 5
      read-only: false
  # json
  jackson:
    # 不返回null
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false


# mybatis配置
mybatis:
  mapper-locations: classpath:/mapper/*.xml    # mapper映射文件位置
  type-aliases-package: com.poi.domain   # 实体类所在的位置
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   #用于控制台打印sql语句

# 注册中心

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8000/eureka


