# 服务注册中心 (单节点)
server:
  port: 8000
eureka:
  instance:
    hostname: localhost
  client:
    # 表示是否从Eureka Server获取注册信息,默认为true.
    fetch-registry: false
    register-with-eureka: false # 表示是否将自己注册到Eureka Server,默认为true.
    service-url:
      # 设置与Eureka Server的地址
      defaultZone: "https://${eureka.instance.hostname}:${server.port}/eureka/"